language: rust

cache:
  directories:
      - target

rust:
  - 1.21.0 # minimum version of compiler supported
  - nightly
  - beta
  - stable

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - (cd interpreter &&
      travis-cargo build &&
      travis-cargo test)
  - (cd assembler &&
      travis-cargo build &&
      travis-cargo test)
  - (travis-cargo build &&
     travis-cargo test)

env:
    global:
        - LD_LIBRARY_PATH: /usr/local/lib

install:
    # SDL2
    - curl -O http://www.libsdl.org/release/SDL2-2.0.0.tar.gz
    - tar -xzvf SDL2-2.0.0.tar.gz
    - (cd SDL2-2.0.0 && ./configure && make && sudo make install)