language: rust

cache:
  directories:
      - target

rust:
  - nightly
  - beta

before_script:
  - git clone --depth 1 https://github.com/huonw/travis-cargo
  - ln -s ./travis-cargo/travis-cargo.py tc

before_install:
  - sudo add-apt-repository ppa:team-xbmc/ppa -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install libsdl2-dev

script:
  - (cd interpreter &&
      ../tc cargo build &&
      ../tc cargo test)
  - (cd assembler &&
     ../tc cargo build &&
     ../tc cargo test)
  - (./tc cargo build &&
     ./tc cargo test)
