language: rust

cache:
  directories:
      - target

rust:
  - nightly
  - beta

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

before_install:
  - sudo add-apt-repository ppa:team-xbmc/ppa -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install libsdl2-dev

script:
  - (cd interpreter &&
      travis-cargo build &&
      travis-cargo test)
  - (cd assembler &&
      travis-cargo build &&
      travis-cargo test)
  - (travis-cargo build &&
     travis-cargo test)
