language: rust
sudo: false

cache:
  directories:
      - target

rust:
  - nightly
  - beta

before_script:
  - git clone --depth 1 https://github.com/huonw/travis-cargo
  - ln -s ./travis-cargo/travis-cargo.py tc

script:
  - |
      cd interpreter &&
      ../tc cargo build &&
      ../tc cargo test
  - |
      cd assembler &&
      ../tc cargo build &&
      ../tc cargo test
  - |
      ./tc cargo build &&
      ./tc cargo test
