[package]

name = "hack-interpreter"
version = "0.0.1"
authors = ["Kevin Butler <haqkrs@gmail.com>"]

[lib]
name = "hack_interpreter"
path = "src/lib.rs"

[dependencies]
log = "*"
docopt = "*"
rustc-serialize = "*"

[dependencies.drawille]
git = "https://github.com/Ryman/drawille-rs"

[dev-dependencies]
tempdir = "*"
glob = "*"

