[package]

name = "hack_interpreter"
version = "0.0.1"
authors = ["Kevin Butler <haqkrs@gmail.com>"]

[dependencies.hack_assembler]
path = "../assembler"

[dependencies]
log = "0.3"

[dev-dependencies]
tempdir = "0.3"
glob = "0.2"

[features]
unstable = []
